name: Build0

on:
    push:
        branches:
            - "build/*"

env:
    NAME: uias

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4.1.1

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Get version and release from branch
              id: get_version
              run: |
                  BRANCH_NAME=${GITHUB_REF#refs/heads/}
                  TMP=${BRANCH_NAME#build/}
                  if [[ "$TMP" == *-* ]]; then
                    VERSION=${TMP%-*}
                    RELEASE=${TMP#*-}
                  else
                    VERSION=$TMP
                    RELEASE=1
                  fi
                  echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
                  echo "RELEASE=$RELEASE" >> $GITHUB_OUTPUT

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Pack tar.gz
              run: |
                  product="${{ env.NAME }}-${{ steps.get_version.outputs.VERSION }}"
                  tar zcvf "${product}.tar.gz" --transform "s/^dist/${product}/" dist

            - name: build rpm package
              env:
                  RPMSPEC: uias.spec
                  RPMBUILDBIMG: outsrkem/rpmbuild:4.14.3-rocky8
                  TARNAME: ${{ env.NAME }}-${{ steps.get_version.outputs.VERSION }}.tar.gz
                  TAG_VERSION: ${{ steps.get_version.outputs.VERSION }}
                  TAG_RELEASE: ${{ steps.get_version.outputs.RELEASE }}

              run: |
                  ARGS=(
                    -bb
                    --define "_version ${TAG_VERSION}"
                    --define "_release ${TAG_RELEASE}"
                    --define "dist .el6"
                    SPECS/rpm.spec
                  )

                  docker run -i --rm \
                    -v "$(pwd)/.cid/${RPMSPEC}:/root/rpmbuild/SPECS/rpm.spec" \
                    -v "$(pwd)/${TARNAME}:/root/rpmbuild/SOURCES/${TARNAME}" \
                    -v "$(pwd)/rpms:/root/rpmbuild/RPMS" \
                    -w /root/rpmbuild ${RPMBUILDBIMG} \
                    bash -c 'rpmbuild "$@"' _ "${ARGS[@]}"

            - name: Upload to HuaweiCloud OBS
              env:
                  AK: ${{ secrets.HW_ACCESS_KEY_ID }}
                  SK: ${{ secrets.HW_SECRET_ACCESS_KEY }}
                  OBS_ENDPOINT: ${{ vars.OBS_ENDPOINT }}
                  OBS_BUCKET: ${{ vars.OBS_BUCKET }}

              run: |
                  wget -q https://obs-community.obs.cn-north-1.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz
                  tar -xzf obsutil_linux_amd64.tar.gz
                  mv obsutil_linux_amd64_* obsutil
                  chmod 755 obsutil/obsutil

                  ./obsutil/obsutil config -i="$AK" -k="$SK" -e="$OBS_ENDPOINT"

                  find . -type f -name "uias-*.rpm" | while read file; do
                    echo "Uploading RPM: $file"
                    ./obsutil/obsutil cp "$file" $OBS_BUCKET/${{ env.NAME }}/
                  done
